"""empty message

Revision ID: 588e6fbcd78a
Revises: 20dccc767b36
Create Date: 2018-06-11 10:55:25.611697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '588e6fbcd78a'
down_revision = '20dccc767b36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test')
    # ### end Alembic commands ###
