"""empty message

Revision ID: 68e3dd204e66
Revises: 8fa239fe330a
Create Date: 2018-07-05 11:40:33.629500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68e3dd204e66'
down_revision = '8fa239fe330a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('script', sa.Column('description', sa.String(length=512), nullable=True))
    op.drop_index('id_index', table_name='script')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('id_index', 'script', ['id'], unique=False)
    op.drop_column('script', 'description')
    # ### end Alembic commands ###
