"""empty message

Revision ID: 8fa239fe330a
Revises: 588e6fbcd78a
Create Date: 2018-07-04 10:53:45.810891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fa239fe330a'
down_revision = '588e6fbcd78a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('script', sa.Column('paras', sa.JSON(), nullable=True))
    op.add_column('script', sa.Column('r_type', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('script', 'r_type')
    op.drop_column('script', 'paras')
    # ### end Alembic commands ###
